apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xeol-agent-read-only
rules:
- apiGroups: ["apps", ""]
  resources: ["pods","namespaces", "deployments"]
  verbs: ["get", "watch", "list"]
