apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xeol-agent-read-only-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "xeol-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: xeol-agent-read-only
  apiGroup: rbac.authorization.k8s.io
